name: Lean Action CI

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: namespace-profile-argument

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-lake-cache
        if: github.event_name == 'pull_request'
        with:
          marker: ${{ github.event_name }}-lean
      - uses: leanprover/lean-action@v1
        with:
          use-github-cache: false
